"""
Output Assembly Service — Phase 14 implementation.
Aggregates all results into final artifacts (JSON, Gherkin, Markdown).
"""
import json
import uuid
import time
import datetime
from typing import Any, Dict, List, Optional

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, update

from app.core.config import settings
from app.core.logging import log_event, logger
from app.db.models.run import Run
from app.db.models.behaviour_scenario import BehaviourScenario
from app.db.models.artifact import Artifact
from app.services.storage_service import storage_service


class OutputAssemblyService:
    """
    Assembles final artifacts for the run.
    """

    @staticmethod
    async def run_assembly(db: AsyncSession, run_id: str, state: Dict[str, Any]) -> Dict[str, Any]:
        """
        Main entry point for Phase 14 assembly.
        """
        start_time = time.time()
        log_event("output_assembly_started", run_id=run_id)

        # 1. Fetch data from DB
        result = await db.execute(
            select(BehaviourScenario).where(BehaviourScenario.run_id == run_id)
        )
        all_scenarios = result.scalars().all()
        
        accepted_scenarios = [s for s in all_scenarios if s.final_status in ["accepted", "accepted_with_warning"]]
        
        final_artifacts_list = []

        # 2. Build final_output.json
        final_output = {
            "run_id": run_id,
            "status": "completed",
            "completed_at": datetime.datetime.utcnow().isoformat(),
            "summary": {
                "total_scenarios": len(all_scenarios),
                "accepted_scenarios": len(accepted_scenarios),
                "rejected_scenarios": len([s for s in all_scenarios if s.final_status == "rejected"]),
            },
            "scenarios": [
                {
                    "scenario_id": s.id,
                    "title": s.scenario_title,
                    "feature": s.feature,
                    "priority": s.final_priority,
                    "confidence": s.final_confidence,
                    "gherkin": s.gherkin_text,
                } for s in accepted_scenarios
            ],
            "metadata": state.get("metadata", {})
        }

        if settings.SAVE_FINAL_OUTPUT_JSON:
            uri = await OutputAssemblyService._save_artifact(
                db, run_id, "final_output", "final_output.json", 
                json.dumps(final_output, indent=2).encode("utf-8"), "application/json"
            )
            final_artifacts_list.append({"type": "final_output", "uri": uri})

        # 3. Build scenarios.gherkin
        if settings.SAVE_GHERKIN_EXPORT and accepted_scenarios:
            gherkin_text = f"# Generated by UI-TestGen\n# Run ID: {run_id}\n\n"
            # Group by feature
            features = {}
            for s in accepted_scenarios:
                if s.feature not in features:
                    features[s.feature] = []
                features[s.feature].append(s)
            
            for feature_name, scs in features.items():
                gherkin_text += f"Feature: {feature_name}\n\n"
                for s in scs:
                    gherkin_text += f"  Scenario: {s.scenario_title}\n"
                    # Add indent to each line of gherkin text if needed, 
                    # but usually gherkin_text already has steps.
                    # We'll just append it directly for now.
                    gherkin_text += s.gherkin_text.replace(f"Feature: {s.feature}\n\n", "") + "\n"

            uri = await OutputAssemblyService._save_artifact(
                db, run_id, "gherkin_export", "scenarios.gherkin", 
                gherkin_text.encode("utf-8"), "text/plain"
            )
            final_artifacts_list.append({"type": "gherkin_export", "uri": uri})

        # 4. Build summary_report.md
        if settings.SAVE_MARKDOWN_SUMMARY_REPORT:
            md_text = f"# UI-TestGen Run Summary: {run_id}\n\n"
            md_text += f"**Status:** Completed\n"
            md_text += f"**Accepted Scenarios:** {len(accepted_scenarios)}\n\n"
            md_text += "## Final Scenarios\n\n"
            for s in accepted_scenarios:
                md_text += f"### {s.scenario_title}\n"
                md_text += f"- Priority: {s.final_priority}\n"
                md_text += f"- Confidence: {s.final_confidence:.2f}\n\n"
                md_text += f"```gherkin\n{s.gherkin_text}\n```\n\n"

            uri = await OutputAssemblyService._save_artifact(
                db, run_id, "summary_report", "summary_report.md", 
                md_text.encode("utf-8"), "text/markdown"
            )
            final_artifacts_list.append({"type": "summary_report", "uri": uri})

        # 5. Update Run Status
        await db.execute(
            update(Run).where(Run.id == run_id).values(
                status="completed",
                completed_at=datetime.datetime.utcnow()
            )
        )
        await db.commit()

        log_event("output_assembly_completed", run_id=run_id)

        return {
            "final_output": final_output,
            "final_artifacts": final_artifacts_list
        }

    @staticmethod
    async def _save_artifact(db: AsyncSession, run_id: str, art_type: str, filename: str, content: bytes, mime: str) -> str:
        key = f"final/{run_id}/{filename}"
        uri = storage_service.upload_file(content, key, content_type=mime)
        
        artifact = Artifact(
            id=f"art_{uuid.uuid4().hex[:12]}",
            run_id=run_id,
            artifact_type=art_type,
            node_name="output_assembly",
            storage_uri=uri,
        )
        db.add(artifact)
        return uri
