version: "3.8"
services:
  backend:
    build:
      context: ./be
    ports:
      - "8080:8080"
    volumes:
      - ./be/uploads:/app/uploads
    container_name: ui-testgen-be
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=new_user
      - DB_PASSWORD=new_password
      - DB_NAME=ui_testgen_db

  frontend:
    build:
      context: ./fe
    ports:
      - "3030:80"
    depends_on:
      - backend
    container_name: ui-testgen-fe
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: ui-testgen-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_secret_password
      MYSQL_DATABASE: ui_testgen_db
      MYSQL_USER: new_user
      MYSQL_PASSWORD: new_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
