version: "3.8"
services:
  backend:
    build:
      context: ./be
    ports:
      - "8080:8080"
    volumes:
      - ./be/uploads:/app/uploads
    container_name: ui-testgen-be
    restart: unless-stopped

  frontend:
    build:
      context: ./fe
    ports:
      - "3030:80"
    depends_on:
      - backend
    container_name: ui-testgen-fe
    restart: unless-stopped
