"""Phase 7 input level fields

Revision ID: 397ad6b9f337
Revises: 70da19d7b4d8
Create Date: 2026-05-09 16:05:10.301536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397ad6b9f337'
down_revision: Union[str, Sequence[str], None] = '70da19d7b4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('input_level_confidence', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('input_level_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'input_level_reason')
    op.drop_column('runs', 'input_level_confidence')
    # ### end Alembic commands ###
