"""Phase 4 graph tracking

Revision ID: 3b8f099a55ae
Revises: 636a29843f2e
Create Date: 2026-05-09 14:30:21.514726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8f099a55ae'
down_revision: Union[str, Sequence[str], None] = '636a29843f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE runs SET current_phase = 'created' WHERE current_phase IS NULL")
    op.alter_column('runs', 'current_phase',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_runs_graph_thread_id'), 'runs', ['graph_thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_graph_thread_id'), table_name='runs')
    op.alter_column('runs', 'current_phase',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
