"""Phase 9 flow completeness fields

Revision ID: 442cd0b6012a
Revises: efec6290c227
Create Date: 2026-05-09 16:24:14.991787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442cd0b6012a'
down_revision: Union[str, Sequence[str], None] = 'efec6290c227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flows', sa.Column('completeness_status', sa.String(), nullable=True))
    op.add_column('flows', sa.Column('scenario_eligibility', sa.String(), nullable=True))
    op.add_column('flows', sa.Column('missing_step_penalty', sa.Float(), nullable=False))
    op.add_column('flows', sa.Column('adjusted_confidence', sa.Float(), nullable=False))
    op.add_column('flows', sa.Column('missing_step_warnings_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flows', 'missing_step_warnings_json')
    op.drop_column('flows', 'adjusted_confidence')
    op.drop_column('flows', 'missing_step_penalty')
    op.drop_column('flows', 'scenario_eligibility')
    op.drop_column('flows', 'completeness_status')
    # ### end Alembic commands ###
