"""Add behaviour_scenarios table

Revision ID: 48625aed8017
Revises: d90bc9652cfe
Create Date: 2026-05-09 16:53:22.248877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48625aed8017'
down_revision: Union[str, Sequence[str], None] = 'd90bc9652cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviour_scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('flow_id', sa.String(), nullable=False),
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=True),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('scenario_title', sa.String(), nullable=False),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('grounding_mode', sa.String(), nullable=False),
    sa.Column('gherkin_text', sa.String(), nullable=False),
    sa.Column('structured_steps_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('initial_confidence', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['behaviour_intents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behaviour_scenarios_flow_id'), 'behaviour_scenarios', ['flow_id'], unique=False)
    op.create_index(op.f('ix_behaviour_scenarios_intent_id'), 'behaviour_scenarios', ['intent_id'], unique=False)
    op.create_index(op.f('ix_behaviour_scenarios_run_id'), 'behaviour_scenarios', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behaviour_scenarios_run_id'), table_name='behaviour_scenarios')
    op.drop_index(op.f('ix_behaviour_scenarios_intent_id'), table_name='behaviour_scenarios')
    op.drop_index(op.f('ix_behaviour_scenarios_flow_id'), table_name='behaviour_scenarios')
    op.drop_table('behaviour_scenarios')
    # ### end Alembic commands ###
