"""Add curation fields to behaviour_scenarios

Revision ID: 50d620491557
Revises: c3934c2c3dfd
Create Date: 2026-05-09 17:12:50.724006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d620491557'
down_revision: Union[str, Sequence[str], None] = 'c3934c2c3dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behaviour_scenarios', sa.Column('final_status', sa.String(), nullable=False))
    op.add_column('behaviour_scenarios', sa.Column('final_priority', sa.String(), nullable=False))
    op.add_column('behaviour_scenarios', sa.Column('priority_score', sa.Float(), nullable=False))
    op.add_column('behaviour_scenarios', sa.Column('priority_reason', sa.String(), nullable=True))
    op.add_column('behaviour_scenarios', sa.Column('curation_reason', sa.String(), nullable=True))
    op.add_column('behaviour_scenarios', sa.Column('duplicate_group_id', sa.String(), nullable=True))
    op.add_column('behaviour_scenarios', sa.Column('is_canonical_scenario', sa.Boolean(), nullable=False))
    op.add_column('behaviour_scenarios', sa.Column('curated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behaviour_scenarios', 'curated_at')
    op.drop_column('behaviour_scenarios', 'is_canonical_scenario')
    op.drop_column('behaviour_scenarios', 'duplicate_group_id')
    op.drop_column('behaviour_scenarios', 'curation_reason')
    op.drop_column('behaviour_scenarios', 'priority_reason')
    op.drop_column('behaviour_scenarios', 'priority_score')
    op.drop_column('behaviour_scenarios', 'final_priority')
    op.drop_column('behaviour_scenarios', 'final_status')
    # ### end Alembic commands ###
