"""pipeline_v2_refactor

Revision ID: 617efa320277
Revises: c7e2a9b04f11
Create Date: 2026-05-16 10:26:27.016677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '617efa320277'
down_revision: Union[str, Sequence[str], None] = 'c7e2a9b04f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Delete all old data
    op.execute("TRUNCATE TABLE runs CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screen_behaviour_intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('state_id', sa.String(), nullable=False),
    sa.Column('source_group_id', sa.String(), nullable=False),
    sa.Column('intent_name', sa.String(), nullable=False),
    sa.Column('intent_kind', sa.String(), nullable=False),
    sa.Column('local_user_goal', sa.String(), nullable=False),
    sa.Column('primary_action_json', sa.JSON(), nullable=True),
    sa.Column('required_input_groups_json', sa.JSON(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('raw_result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['ui_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screen_behaviour_intents_run_id'), 'screen_behaviour_intents', ['run_id'], unique=False)
    op.create_index(op.f('ix_screen_behaviour_intents_state_id'), 'screen_behaviour_intents', ['state_id'], unique=False)
    op.drop_constraint(op.f('images_duplicate_group_id_fkey'), 'images', type_='foreignkey')
    op.drop_index(op.f('ix_duplicate_group_members_duplicate_group_id'), table_name='duplicate_group_members')
    op.drop_index(op.f('ix_duplicate_group_members_id'), table_name='duplicate_group_members')
    op.drop_index(op.f('ix_duplicate_group_members_image_id'), table_name='duplicate_group_members')
    op.drop_index(op.f('ix_duplicate_group_members_run_id'), table_name='duplicate_group_members')
    op.drop_table('duplicate_group_members')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('ix_duplicate_groups_id'), table_name='duplicate_groups')
    op.drop_index(op.f('ix_duplicate_groups_run_id'), table_name='duplicate_groups')
    op.drop_table('duplicate_groups')
    op.add_column('behaviour_intents', sa.Column('source_group_id', sa.String(), nullable=True))
    op.add_column('behaviour_intents', sa.Column('source_screen_intent_id', sa.String(), nullable=True))
    op.add_column('behaviour_intents', sa.Column('source_transition_ids_json', sa.JSON(), nullable=True))
    op.add_column('flow_transitions', sa.Column('source_group_id', sa.String(), nullable=True))
    op.add_column('flow_transitions', sa.Column('source_screen_intent_id', sa.String(), nullable=True))
    op.drop_column('images', 'duplicate_status')
    op.drop_column('images', 'is_canonical')
    op.drop_column('images', 'duplicate_reason')
    op.drop_column('images', 'preprocessing_json')
    op.drop_column('images', 'phash')
    op.drop_column('images', 'duplicate_confidence')
    op.drop_column('images', 'normalized_uri')
    op.drop_column('images', 'duplicate_type')
    op.drop_column('images', 'duplicate_group_id')
    op.drop_column('images', 'dhash')
    op.drop_column('runs', 'canonical_images')
    op.drop_column('runs', 'duplicate_groups_count')
    op.alter_column('ui_elements', 'text',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='text::json')
    op.add_column('ui_states', sa.Column('interaction_groups_json', sa.JSON(), nullable=True))
    op.drop_column('ui_states', 'is_canonical')
    op.drop_column('ui_states', 'canonical_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ui_states', sa.Column('canonical_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ui_states', sa.Column('is_canonical', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('ui_states', 'interaction_groups_json')
    op.alter_column('ui_elements', 'text',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('runs', sa.Column('duplicate_groups_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('runs', sa.Column('canonical_images', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('dhash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('duplicate_group_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('duplicate_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('normalized_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('duplicate_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('phash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('preprocessing_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('duplicate_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('is_canonical', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('duplicate_status', sa.VARCHAR(), server_default=sa.text("'not_checked'::character varying"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('images_duplicate_group_id_fkey'), 'images', 'duplicate_groups', ['duplicate_group_id'], ['id'])
    op.drop_column('flow_transitions', 'source_screen_intent_id')
    op.drop_column('flow_transitions', 'source_group_id')
    op.drop_column('behaviour_intents', 'source_transition_ids_json')
    op.drop_column('behaviour_intents', 'source_screen_intent_id')
    op.drop_column('behaviour_intents', 'source_group_id')
    op.create_table('duplicate_groups',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('canonical_image_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duplicate_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('group_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['canonical_image_id'], ['images.id'], name=op.f('duplicate_groups_canonical_image_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('duplicate_groups_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('duplicate_groups_pkey'))
    )
    op.create_index(op.f('ix_duplicate_groups_run_id'), 'duplicate_groups', ['run_id'], unique=False)
    op.create_index(op.f('ix_duplicate_groups_id'), 'duplicate_groups', ['id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('duplicate_group_members',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duplicate_group_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duplicate_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('similarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hash_distance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['duplicate_group_id'], ['duplicate_groups.id'], name=op.f('duplicate_group_members_duplicate_group_id_fkey')),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('duplicate_group_members_image_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('duplicate_group_members_pkey'))
    )
    op.create_index(op.f('ix_duplicate_group_members_run_id'), 'duplicate_group_members', ['run_id'], unique=False)
    op.create_index(op.f('ix_duplicate_group_members_image_id'), 'duplicate_group_members', ['image_id'], unique=False)
    op.create_index(op.f('ix_duplicate_group_members_id'), 'duplicate_group_members', ['id'], unique=False)
    op.create_index(op.f('ix_duplicate_group_members_duplicate_group_id'), 'duplicate_group_members', ['duplicate_group_id'], unique=False)
    op.drop_index(op.f('ix_screen_behaviour_intents_state_id'), table_name='screen_behaviour_intents')
    op.drop_index(op.f('ix_screen_behaviour_intents_run_id'), table_name='screen_behaviour_intents')
    op.drop_table('screen_behaviour_intents')
    # ### end Alembic commands ###
