"""Phase 4 graph tracking

Revision ID: 636a29843f2e
Revises: 72080c62b45b
Create Date: 2026-05-09 14:15:55.851219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636a29843f2e'
down_revision: Union[str, Sequence[str], None] = '72080c62b45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('current_phase', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('current_node', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('progress_percentage', sa.Integer(), nullable=False))
    op.add_column('runs', sa.Column('graph_status', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('graph_thread_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'graph_thread_id')
    op.drop_column('runs', 'graph_status')
    op.drop_column('runs', 'progress_percentage')
    op.drop_column('runs', 'current_node')
    op.drop_column('runs', 'current_phase')
    # ### end Alembic commands ###
