"""Phase 6 ui states and elements tables

Revision ID: 70da19d7b4d8
Revises: 124461ee4d51
Create Date: 2026-05-09 15:34:41.744675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70da19d7b4d8'
down_revision: Union[str, Sequence[str], None] = '124461ee4d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ui_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('page_type', sa.String(), nullable=False),
    sa.Column('state_summary', sa.String(), nullable=True),
    sa.Column('state_signature', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(), nullable=False),
    sa.Column('has_form', sa.Boolean(), nullable=False),
    sa.Column('has_table', sa.Boolean(), nullable=False),
    sa.Column('has_modal', sa.Boolean(), nullable=False),
    sa.Column('has_feedback', sa.Boolean(), nullable=False),
    sa.Column('extraction_status', sa.String(), nullable=False),
    sa.Column('extraction_error', sa.String(), nullable=True),
    sa.Column('raw_extraction_artifact_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_states_id'), 'ui_states', ['id'], unique=False)
    op.create_index(op.f('ix_ui_states_image_id'), 'ui_states', ['image_id'], unique=False)
    op.create_index(op.f('ix_ui_states_run_id'), 'ui_states', ['run_id'], unique=False)
    op.create_table('ui_elements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('state_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('placeholder', sa.String(), nullable=True),
    sa.Column('bbox_xmin', sa.Float(), nullable=True),
    sa.Column('bbox_ymin', sa.Float(), nullable=True),
    sa.Column('bbox_xmax', sa.Float(), nullable=True),
    sa.Column('bbox_ymax', sa.Float(), nullable=True),
    sa.Column('actionable', sa.Boolean(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('is_feedback', sa.Boolean(), nullable=False),
    sa.Column('feedback_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['ui_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ui_elements_id'), 'ui_elements', ['id'], unique=False)
    op.create_index(op.f('ix_ui_elements_image_id'), 'ui_elements', ['image_id'], unique=False)
    op.create_index(op.f('ix_ui_elements_run_id'), 'ui_elements', ['run_id'], unique=False)
    op.create_index(op.f('ix_ui_elements_state_id'), 'ui_elements', ['state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ui_elements_state_id'), table_name='ui_elements')
    op.drop_index(op.f('ix_ui_elements_run_id'), table_name='ui_elements')
    op.drop_index(op.f('ix_ui_elements_image_id'), table_name='ui_elements')
    op.drop_index(op.f('ix_ui_elements_id'), table_name='ui_elements')
    op.drop_table('ui_elements')
    op.drop_index(op.f('ix_ui_states_run_id'), table_name='ui_states')
    op.drop_index(op.f('ix_ui_states_image_id'), table_name='ui_states')
    op.drop_index(op.f('ix_ui_states_id'), table_name='ui_states')
    op.drop_table('ui_states')
    # ### end Alembic commands ###
