"""Phase 3 duplicate detection schema

Revision ID: 72080c62b45b
Revises: b34603f6d5cf
Create Date: 2026-05-09 13:48:42.088067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72080c62b45b'
down_revision: Union[str, Sequence[str], None] = 'b34603f6d5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('canonical_image_id', sa.String(), nullable=False),
    sa.Column('duplicate_type', sa.String(), nullable=False),
    sa.Column('group_reason', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_groups_id'), 'duplicate_groups', ['id'], unique=False)
    op.create_index(op.f('ix_duplicate_groups_run_id'), 'duplicate_groups', ['run_id'], unique=False)
    op.create_table('duplicate_group_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('duplicate_group_id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('duplicate_type', sa.String(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('hash_distance', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_group_id'], ['duplicate_groups.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_group_members_duplicate_group_id'), 'duplicate_group_members', ['duplicate_group_id'], unique=False)
    op.create_index(op.f('ix_duplicate_group_members_id'), 'duplicate_group_members', ['id'], unique=False)
    op.create_index(op.f('ix_duplicate_group_members_image_id'), 'duplicate_group_members', ['image_id'], unique=False)
    op.create_index(op.f('ix_duplicate_group_members_run_id'), 'duplicate_group_members', ['run_id'], unique=False)
    op.add_column('images', sa.Column('duplicate_status', sa.String(), server_default='not_checked', nullable=False))
    op.add_column('images', sa.Column('duplicate_group_id', sa.String(), nullable=True))
    op.add_column('images', sa.Column('is_canonical', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('images', sa.Column('duplicate_type', sa.String(), nullable=True))
    op.add_column('images', sa.Column('duplicate_reason', sa.String(), nullable=True))
    op.add_column('images', sa.Column('duplicate_confidence', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('phash', sa.String(), nullable=True))
    op.add_column('images', sa.Column('dhash', sa.String(), nullable=True))
    op.create_foreign_key(None, 'images', 'duplicate_groups', ['duplicate_group_id'], ['id'])
    op.add_column('runs', sa.Column('canonical_images', sa.Integer(), server_default='0', nullable=False))
    op.add_column('runs', sa.Column('duplicate_groups_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'duplicate_groups_count')
    op.drop_column('runs', 'canonical_images')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'dhash')
    op.drop_column('images', 'phash')
    op.drop_column('images', 'duplicate_confidence')
    op.drop_column('images', 'duplicate_reason')
    op.drop_column('images', 'duplicate_type')
    op.drop_column('images', 'is_canonical')
    op.drop_column('images', 'duplicate_group_id')
    op.drop_column('images', 'duplicate_status')
    op.drop_index(op.f('ix_duplicate_group_members_run_id'), table_name='duplicate_group_members')
    op.drop_index(op.f('ix_duplicate_group_members_image_id'), table_name='duplicate_group_members')
    op.drop_index(op.f('ix_duplicate_group_members_id'), table_name='duplicate_group_members')
    op.drop_index(op.f('ix_duplicate_group_members_duplicate_group_id'), table_name='duplicate_group_members')
    op.drop_table('duplicate_group_members')
    op.drop_index(op.f('ix_duplicate_groups_run_id'), table_name='duplicate_groups')
    op.drop_index(op.f('ix_duplicate_groups_id'), table_name='duplicate_groups')
    op.drop_table('duplicate_groups')
    # ### end Alembic commands ###
