"""Add preprocessing_json to images

Revision ID: b34603f6d5cf
Revises: f41a31aa6c81
Create Date: 2026-05-09 13:25:51.977493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34603f6d5cf'
down_revision: Union[str, Sequence[str], None] = 'f41a31aa6c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('preprocessing_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'preprocessing_json')
    # ### end Alembic commands ###
