"""Add validation fields to behaviour_scenarios

Revision ID: c3934c2c3dfd
Revises: 48625aed8017
Create Date: 2026-05-09 17:01:17.344159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3934c2c3dfd'
down_revision: Union[str, Sequence[str], None] = '48625aed8017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behaviour_scenarios', sa.Column('grounding_score', sa.Float(), nullable=False))
    op.add_column('behaviour_scenarios', sa.Column('evidence_coverage_score', sa.Float(), nullable=False))
    op.add_column('behaviour_scenarios', sa.Column('hallucination_flags_json', sa.JSON(), nullable=True))
    op.add_column('behaviour_scenarios', sa.Column('validation_issues_json', sa.JSON(), nullable=True))
    op.add_column('behaviour_scenarios', sa.Column('revision_suggestions_json', sa.JSON(), nullable=True))
    op.add_column('behaviour_scenarios', sa.Column('final_confidence', sa.Float(), nullable=False))
    op.add_column('behaviour_scenarios', sa.Column('validated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behaviour_scenarios', 'validated_at')
    op.drop_column('behaviour_scenarios', 'final_confidence')
    op.drop_column('behaviour_scenarios', 'revision_suggestions_json')
    op.drop_column('behaviour_scenarios', 'validation_issues_json')
    op.drop_column('behaviour_scenarios', 'hallucination_flags_json')
    op.drop_column('behaviour_scenarios', 'evidence_coverage_score')
    op.drop_column('behaviour_scenarios', 'grounding_score')
    # ### end Alembic commands ###
