"""Add behaviour_intents table

Revision ID: d90bc9652cfe
Revises: 442cd0b6012a
Create Date: 2026-05-09 16:33:53.460583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd90bc9652cfe'
down_revision: Union[str, Sequence[str], None] = '442cd0b6012a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviour_intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('flow_id', sa.String(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=True),
    sa.Column('intent_name', sa.String(), nullable=False),
    sa.Column('behaviour_domain', sa.String(), nullable=False),
    sa.Column('behaviour_outcome', sa.String(), nullable=False),
    sa.Column('user_goal', sa.String(), nullable=False),
    sa.Column('scenario_type_hint', sa.String(), nullable=False),
    sa.Column('expected_grounding', sa.String(), nullable=False),
    sa.Column('should_generate', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(), nullable=False),
    sa.Column('evidence_state_ids_json', sa.JSON(), nullable=False),
    sa.Column('evidence_transition_ids_json', sa.JSON(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('raw_result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behaviour_intents_flow_id'), 'behaviour_intents', ['flow_id'], unique=False)
    op.create_index(op.f('ix_behaviour_intents_intent_name'), 'behaviour_intents', ['intent_name'], unique=False)
    op.create_index(op.f('ix_behaviour_intents_run_id'), 'behaviour_intents', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behaviour_intents_run_id'), table_name='behaviour_intents')
    op.drop_index(op.f('ix_behaviour_intents_intent_name'), table_name='behaviour_intents')
    op.drop_index(op.f('ix_behaviour_intents_flow_id'), table_name='behaviour_intents')
    op.drop_table('behaviour_intents')
    # ### end Alembic commands ###
