"""Phase 4 graph dates

Revision ID: df6111b039b2
Revises: 3b8f099a55ae
Create Date: 2026-05-09 14:34:12.114936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6111b039b2'
down_revision: Union[str, Sequence[str], None] = '3b8f099a55ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('graph_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('graph_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'graph_completed_at')
    op.drop_column('runs', 'graph_started_at')
    # ### end Alembic commands ###
