"""Phase 8 flows and transitions tables

Revision ID: efec6290c227
Revises: 397ad6b9f337
Create Date: 2026-05-09 16:16:06.674719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efec6290c227'
down_revision: Union[str, Sequence[str], None] = '397ad6b9f337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('flow_type', sa.String(), nullable=False),
    sa.Column('input_level', sa.String(), nullable=False),
    sa.Column('start_state_id', sa.String(), nullable=True),
    sa.Column('ordered_state_ids_json', sa.JSON(), nullable=False),
    sa.Column('paths_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(), nullable=False),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_id'), 'flows', ['id'], unique=False)
    op.create_index(op.f('ix_flows_run_id'), 'flows', ['run_id'], unique=False)
    op.create_table('flow_transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('flow_id', sa.String(), nullable=False),
    sa.Column('from_state_id', sa.String(), nullable=False),
    sa.Column('to_state_id', sa.String(), nullable=False),
    sa.Column('transition_type', sa.String(), nullable=False),
    sa.Column('hypothesized_action', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_transitions_flow_id'), 'flow_transitions', ['flow_id'], unique=False)
    op.create_index(op.f('ix_flow_transitions_from_state_id'), 'flow_transitions', ['from_state_id'], unique=False)
    op.create_index(op.f('ix_flow_transitions_id'), 'flow_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_flow_transitions_run_id'), 'flow_transitions', ['run_id'], unique=False)
    op.create_index(op.f('ix_flow_transitions_to_state_id'), 'flow_transitions', ['to_state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_transitions_to_state_id'), table_name='flow_transitions')
    op.drop_index(op.f('ix_flow_transitions_run_id'), table_name='flow_transitions')
    op.drop_index(op.f('ix_flow_transitions_id'), table_name='flow_transitions')
    op.drop_index(op.f('ix_flow_transitions_from_state_id'), table_name='flow_transitions')
    op.drop_index(op.f('ix_flow_transitions_flow_id'), table_name='flow_transitions')
    op.drop_table('flow_transitions')
    op.drop_index(op.f('ix_flows_run_id'), table_name='flows')
    op.drop_index(op.f('ix_flows_id'), table_name='flows')
    op.drop_table('flows')
    # ### end Alembic commands ###
