import requests
import json
import time
from PIL import Image as PILImage, ImageDraw

BASE = 'http://localhost:8000/api/v1'

def create_realistic_img(name, noise_pixel=None):
    img = PILImage.new('RGB', (1440, 900), color=(245, 245, 245))
    draw = ImageDraw.Draw(img)
    draw.rectangle([0, 0, 1440, 60], fill=(30, 30, 80))
    draw.text((20, 15), 'Duplicate Test', fill='white')
    draw.rectangle([100, 100, 500, 500], fill='white', outline='gray')
    draw.text((120, 120), 'Main Content', fill='black')
    
    if noise_pixel:
        draw.point(noise_pixel, fill=(255, 0, 0))
        
    img.save(name)
    return name

# Create test images
create_realistic_img('img_original.png')
create_realistic_img('img_exact.png') # Exact same bytes
create_realistic_img('img_near.png', noise_pixel=(500, 500)) # 1 pixel difference

# 1. Create run
r = requests.post(f'{BASE}/runs', json={'project_name': 'Phase 3 Test'})
run_id = r.json()['run_id']
print(f'Created run: {run_id}')

# 2. Upload
files = [
    ('files', ('original.png', open('img_original.png','rb'), 'image/png')),
    ('files', ('exact.png', open('img_exact.png','rb'), 'image/png')),
    ('files', ('near.png', open('img_near.png','rb'), 'image/png')),
]
r = requests.post(f'{BASE}/runs/{run_id}/images', files=files)
print(f'Upload: {r.status_code}, uploaded={r.json()["uploaded_count"]}')

# 3. Submit
r = requests.post(f'{BASE}/runs/{run_id}/submit')
print(f'Submit: {r.status_code}')

# 4. Wait
print('Waiting 20s for worker...')
time.sleep(20)

# 5. Check run details
r = requests.get(f'{BASE}/runs/{run_id}')
run = r.json()
print(f'\nRun status: {run["status"]}')
print(f'  valid_images: {run["valid_images"]}')
print(f'  canonical_images: {run["canonical_images"]}')
print(f'  duplicate_groups: {run["duplicate_groups_count"]}')

# 6. Check report
r = requests.get(f'{BASE}/runs/{run_id}/duplicate-report')
if r.status_code == 200:
    report = r.json()
    print(f'\nDuplicate Report:')
    print(f'  Total valid: {report["total_valid_images"]}')
    print(f'  Canonical: {report["canonical_images_count"]}')
    print(f'  Duplicates: {report["duplicate_images_count"]}')
    for g in report['duplicate_groups']:
        print(f'  Group {g["id"]}: type={g["type"]}, canonical={g["canonical_id"]}, members={g["members"]}')
else:
    print(f'Report error: {r.status_code} {r.text}')

# 7. Check images filter
r = requests.get(f'{BASE}/runs/{run_id}/images', params={'is_canonical': True})
print(f'\nCanonical images count: {r.json()["total"]}')
for img in r.json()['images']:
    print(f'  - {img["image_id"]}: {img["original_filename"]} (status: {img["duplicate_status"]})')

r = requests.get(f'{BASE}/runs/{run_id}/images', params={'is_canonical': False})
print(f'Duplicate images count: {r.json()["total"]}')
for img in r.json()['images']:
    print(f'  - {img["image_id"]}: {img["original_filename"]} (status: {img["duplicate_status"]}, reason: {img.get("duplicate_reason", "none")})')

# 8. Check Graph Status
r = requests.get(f'{BASE}/runs/{run_id}/graph-status')
if r.status_code == 200:
    gstatus = r.json()
    print(f'\nGraph Status:')
    print(f'  graph_status: {gstatus["graph_status"]}')
    print(f'  current_phase: {gstatus["current_phase"]}')
    print(f'  current_node: {gstatus["current_node"]}')
    print(f'  progress_percentage: {gstatus["progress_percentage"]}')
else:
    print(f'Graph status error: {r.status_code} {r.text}')

# 9. Check Artifacts
r = requests.get(f'{BASE}/runs/{run_id}/artifacts')
if r.status_code == 200:
    arts = r.json()
    print(f'\nArtifacts: {arts["total"]}')
    for a in arts['artifacts']:
        print(f'  - {a["type"]} generated by {a["node_name"]}')
else:
    print(f'Artifacts error: {r.status_code} {r.text}')

